# Esta configuraci칩n se aplica a TODOS los servicios clientes
eureka:
  client:
    # Ahora, todos los servicios buscar치n Eureka en esta direcci칩n
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # Prefiere usar la IP en lugar del hostname (m치s confiable)
    prefer-ip-address: true