server:
  port: 8080  # Puerto del API Gateway

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://iam-service:8081/api/v1/jwks/.well-known/jwks.json"

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:5173"
              - "https://app-cobox.web.app"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: iam-service-docs
          uri: lb://iam-service
          predicates:
            - Path=/iam-service/v3/api-docs/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader

        - id: iam-service-route
          uri: lb://iam-service
          predicates:
            - Path=/api/v1/authentication/**,/api/v1/roles/**,/api/v1/users/**,/api/v1/jwks/**
          filters:
            - PreserveHostHeader

        - id: fleet-service-docs
          uri: lb://fleet-service
          predicates:
            - Path=/fleet-service/v3/api-docs/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader

        - id: fleet-service-route
          uri: lb://fleet-service
          predicates:
            - Path=/api/v1/drivers/**,/api/v1/routes/**,/api/v1/vehicles/**
          filters:
            - PreserveHostHeader

        - id: delivery-service-docs
          uri: lb://delivery-service
          predicates:
            - Path=/delivery-service/v3/api-docs/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader

        - id: delivery-service-route
          uri: lb://delivery-service
          predicates:
            - Path=/api/v1/client/**,/api/v1/orders/**
          filters:
            - PreserveHostHeader

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: iam-service
        url: /iam-service/v3/api-docs
      - name: delivery-service
        url: /delivery-service/v3/api-docs
      - name: fleet-service
        url: /fleet-service/v3/api-docs
