version: "3.9"

services:
  config-service:
    build: ./config-service
    container_name: config-service
    environment:
      - SPRING_PROFILES_ACTIVE=native
    ports: [ "8888:8888" ]
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 10

  eureka-service:
    build: ./eureka-service
    container_name: eureka-service
    depends_on:
      config-service:
        condition: service_healthy
    ports: [ "8761:8761" ]   # solo para ver dashboard en local
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 10

  iam-service:
    build: ./iam-service
    container_name: iam-service
    depends_on:
      eureka-service:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=${IAM_POSTGRES_HOST}
      - POSTGRES_PORT=${IAM_POSTGRES_PORT}
      - POSTGRES_DATABASE=${IAM_POSTGRES_DATABASE}
      - POSTGRES_USER=${IAM_POSTGRES_USER}
      - POSTGRES_PASSWORD=${IAM_POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 10

  fleet-service:
    build: ./fleet-service
    container_name: fleet-service
    depends_on:
      iam-service:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=${FLEET_POSTGRES_HOST}
      - POSTGRES_PORT=${FLEET_POSTGRES_PORT}
      - POSTGRES_DATABASE=${FLEET_POSTGRES_DATABASE}
      - POSTGRES_USER=${FLEET_POSTGRES_USER}
      - POSTGRES_PASSWORD=${FLEET_POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 10

  delivery-service:
    build: ./delivery-service
    container_name: delivery-service
    depends_on:
      iam-service:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=${DELIVERY_POSTGRES_HOST}
      - POSTGRES_PORT=${DELIVERY_POSTGRES_PORT}
      - POSTGRES_DATABASE=${DELIVERY_POSTGRES_DATABASE}
      - POSTGRES_USER=${DELIVERY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DELIVERY_POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8083/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 10

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    depends_on:
      eureka-service:
        condition: service_healthy
      iam-service:
        condition: service_healthy
      fleet-service:
        condition: service_healthy
      delivery-service:
        condition: service_healthy
    ports: [ "8080:8080" ]
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 10
