services:
  # 1. SERVICIO DE BASE DE DATOS POSTGRESQL (Para Entorno Local)
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: admin_postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_postgres -d postgres_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # 2. CONFIG SERVICE
  config-service:
    build: ./config-service
    container_name: config-service
    environment:
      - SPRING_PROFILES_ACTIVE=native
    ports: [ "8888:8888" ]
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  # 3. EUREKA SERVICE
  eureka-service:
    build: ./eureka-service
    container_name: eureka-service
    depends_on:
      config-service:
        condition: service_healthy
    ports: [ "8761:8761" ]
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  # 4. IAM SERVICE
  iam-service:
    build: ./iam-service
    container_name: iam-service
    depends_on:
      eureka-service:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postgres_db
      - POSTGRES_USER=admin_postgres
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  # 5. FLEET SERVICE
  fleet-service:
    build: ./fleet-service
    container_name: fleet-service
    depends_on:
      iam-service:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postgres_db
      - POSTGRES_USER=admin_postgres
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  # 6. DELIVERY SERVICE
  delivery-service:
    build: ./delivery-service
    container_name: delivery-service
    depends_on:
      iam-service:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postgres_db
      - POSTGRES_USER=admin_postgres
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8083/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  # 7. GATEWAY SERVICE (Escalable)
  gateway-service:
    build: ./gateway-service
    depends_on:
      eureka-service:
        condition: service_healthy
      iam-service:
        condition: service_healthy
      fleet-service:
        condition: service_healthy
      delivery-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  # 8. NGINX REVERSE PROXY / LOAD BALANCER
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      gateway-service:
        condition: service_started
    ports:
      - "80:80"   # Puerto HTTP
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped


  # 10. PROMETHEUS
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - gateway-service
    networks:
      - default

  # 11. GRAFANA
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - default

networks:
  default:
    name: microservices_network
