global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'microservices_cobox'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'iam-service:8081', 'fleet-service:8082', 'delivery-service:8083', 'gateway-service:8080', 'eureka-service:8761', 'config-service:8888' ]