spring:
  application:
    # Este es el nombre que Eureka usará.
    # El Gateway lo usará en la ruta: lb://delivery-service
    name: fleet-service
  config:
    import: "optional:configserver:http://localhost:8888"