spring:
  application:
    name: fleet-service
  config:
    import: "optional:configserver:http://config-service:8888"

management:
  endpoints.web.exposure.include: "health,info"
  endpoint.health.probes.enabled: true