server:
  port: 8888

spring:
  application:
    name: config-service # Nombre con el que se registrar치 en Eureka
  # --- Configuraci칩n del Servidor de Configuraci칩n (Modo Nativo) ---
  profiles:
    # 1. Le dice a Spring que active el perfil "native" (archivos locales)
    active: native
  cloud:
    config:
      server:
        native:
          # 2. Le dice d칩nde buscar los archivos YML
          # "classpath:/config/" apunta a la carpeta "src/main/resources/config/"
          search-locations: classpath:/config/
